### ISSUE TITLE
[Window-Chrome-2880px-게시글 목록] css 수정 요청

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#1]
**버그 설명**
배율에 따라서 게시글 작성 버튼의 위치가 바뀝니다.

**재현하는 방법**
동작을 재현하는 단계:
게시글 리스트 화면에서 배율 조정

**예상한 동작**
게시글 목록위에 게시글 작성 버튼이 있을 것이라고 생각했습니다.

**스크린샷**
<img width="621" alt="image" src="https://github.com/user-attachments/assets/86848081-d2cf-4a54-add3-286c8804f21f" />

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
![image](https://github.com/user-attachments/assets/0384ea0c-cf57-4b1e-9e2c-bb634e9ae22d)
수정 하였습니다

https://github.com/gsandoo/2-sando-kang-community-fe-react/commit/9d4c88cd0455a3dce88b79aaecd469a4f55de9dd
