### ISSUE TITLE
[Window-Chrome-2880px-회원정보 수정] 회원정보 수정 이메일 부분 제안

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#10]
**버그 설명**
회원정보 수정 페이지의 이메일 부분은 수정이 불가능하게 되어있는데, 사용자 입장에서 수정이 가능한 닉네임 부분과 수정이 불가능한 이메일 부분이 동일한 CSS로 적용이 되어있어서 헷갈릴 것 같습니다.

**재현하는 방법**
동작을 재현하는 단계:
로그인 후, 회원 정보 수정 페이지로 이동

**예상한 동작**
이메일 부분은 입력이 가능한 부분과 다른 CSS로 적용되어 있을 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/c8e7dcea-d8bd-4d8a-acf1-3f262e10c567)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
아하 감사합니다, 수정하도록 하겠습니다

**Comment by gsandoo** [comment]
[Fix: resolve issue 100-hours-a-week/2-sando-kang-community-issue #10](https://github.com/gsandoo/2-sando-kang-community-fe-react/commit/6690b1e2ceb135e2803a242c86e0b2786b3a0754)

![image](https://github.com/user-attachments/assets/243544e2-8cef-4dc3-a18d-05c8b844c523)
