### ISSUE TITLE
상단 아우말 대잔치 클릭시 상호작용 관련 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-sando-kang-community-issue#11]
**버그 설명**
- 상단 아우말 대잔치 클릭시 아무런 상호작용이 되지 않음

**재현하는 방법**
- 상단 아무말 대잔치 클릭

**예상한 동작**
- 포스트 목록 페이지로 이동

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

**데스크톱(다음 정보를 작성해 주세요):**
 - chrome

**스마트폰(다음 정보를 입력하세요):**
 
**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정 완료
