### ISSUE TITLE
[Window-Chrome-2880px-회원정보 수정] 회원정보 수정 페이지의 수정 불가능 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#12]
**버그 설명**
회원 정보 수정에서 닉네임만 변경해서 진행하면 수정 진행이 되지 않습니다. 기본으로 프로필 사진이 선택되어있지 않아서 파일이 전달되지 않는다는 에러가 뜹니다.

**재현하는 방법**
동작을 재현하는 단계:
회원 정보 수정 페이지로 이동

**예상한 동작**
닉네임만 수정이 가능할 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/654052e8-7c89-4704-aafa-e42f13630713)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
- 사용자 입장에서 프로필  이미지는 수정하고 싶지 않고 닉네임만 수정하고 싶을 수도 있는데, 해당 부분에 대한 수정이 되었으면 좋겠습니다. :)
- 콘솔에서 로그가 출력이 되지 않았으면 좋겠습니다.

**Comment by gsandoo** [comment]
수정 완료
