### ISSUE TITLE
[Window-Chrome-2880px-게시글 상세] 게시글 상세 페이지의 수정/삭제 버튼 노출 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#13]
**버그 설명**
본인이 작성한 게시글이 아님에도 불구하고 수정 삭제 버튼이 출력됩니다.

**재현하는 방법**
동작을 재현하는 단계:
로그인 후, 게시글 상세 페이지로 이동

**예상한 동작**
본인이 작성한 게시글이 아닌 경우에는 수정/삭제 버튼이 출력되지 않을 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/4669efc6-bbca-44cb-812e-dba82f6aa27b)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**

**Comment by gsandoo** [comment]
해결 완료
