### ISSUE TITLE
[Window-Chrome-2880px-게시글 상세] 게시글 상세 페이지의 댓글 버튼 노출 및 수정 가능 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#14]
**버그 설명**
제가 작성한 댓글이 아닌데, 수정/삭제 버튼이 출력되고 수정이 됩니다.

**재현하는 방법**
동작을 재현하는 단계:
로그인 후, 게시글 상세 페이지로 이동

**예상한 동작**
본인이 작성한 댓글이 아닌 경우에는 수정/삭제 버튼이 출력되지 않을 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/84a2d6e8-0ba2-4cf0-8a02-06e0287494c2)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
콘솔 창에 로그가 출력되지 않게 해주세요.
![image](https://github.com/user-attachments/assets/70ac2e22-9576-410c-b4d9-dc72c634c2cf)

**Comment by gsandoo** [comment]
수정 완료
