### ISSUE TITLE
[Window-Chrome-2880px-게시글 추가] 게시글 추가 페이지의 파일 추가 버튼 CSS 짤리는 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#15]
**버그 설명**
게시글 추가할 때 이미지 파일 추가하는 부분의 CSS가 짤리는 현상이 발생합니다.

**재현하는 방법**
동작을 재현하는 단계:
로그인 후, 게시글 목록에서 게시글 추가 버튼 클릭

**예상한 동작**
파일 선택이 제대로 다 보일 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/f3482b8f-5b9b-4600-8889-4f6060939251)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
![image](https://github.com/user-attachments/assets/c8221e02-e80b-4033-8eb6-70b2b9fd0989)
이슈 해결 (2024.12.18)
