### ISSUE TITLE
[Window-Chrome-2880px-게시글 상세] 이미지 등록하지 않은 게시글 추가 시 이미지 엑박 노출 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#16]
**버그 설명**
게시글을 추가할 때, 이미지를 따로 클릭하지 않고 진행했는데, 게시글 상세페이지에 이미지 엑박이뜹니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인 후, 게시글 목록 화면 진입하여 게시글 추가 버튼 클릭
2. 게시글 등록 (제목, 내용만 입력)
3. 등록한 게시글 클릭

**예상한 동작**
게시글을 추가할 때, 이미지를 등록하지 않아도 게시글 상세 페이지에서 문제가 없을 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/da6a7a40-fed6-46bf-8480-dd8de793470a)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
해결
