### ISSUE TITLE
[Window-Chrome-2880px-게시글 상세] 게시글 상세 페이지의 이미지 짤리는 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#17]
**버그 설명**
게시글 추가시 등록한 이미지가 짤립니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인 후, 게시글 상세페이지에서 게시글 추가 버튼 클릭
2. 게시글 추가 (제목,내용만 입력)
3. 게시글 상세페이지에서 게시글 수정 클릭
4. 첨부파일에 이미지 추가해서 수정 진행
5. 해당 게시글 상세 페이지로 이동

**예상한 동작**
이미지가 짤리지 않고 다 보일 것이라고 생각했습니다.

**스크린샷**
게시글 상세 페이지의 사진
![image](https://github.com/user-attachments/assets/0f987ee1-8024-41f4-a0ec-a0a717bd71b1)

등록한 사진의 원본
![ogu-back](https://github.com/user-attachments/assets/c43ba25d-3af5-4460-96e5-67357be6de3f)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정 완료
