### ISSUE TITLE
gif이미지 안움직임 관련 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-sando-kang-community-issue#18]
**버그 설명**
프로필 이미지를 gif 로 하여도 게시글 작성자 이미지는 고정되어서 나오는 현상 발생

**재현하는 방법**
동작을 재현하는 단계:
1. gif 이미지로 프로필 변경
2. 게시글 작성
3. 작성자 프로필 이미지 확인

**예상한 동작**
- gif 동작을 예상함

**스크린샷**

https://github.com/user-attachments/assets/715e78ca-0257-4d8e-9195-725a14354a3a

**데스크톱(다음 정보를 작성해 주세요):**
 - chrome

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
![image](https://github.com/user-attachments/assets/237e4f83-c994-4088-afb3-eab008668560)

헤더, 게시글 상세 페이지의 작성자 프로필 이미지 gif, 게시글에 업로드한 gif가 움직이지 않네요..!! 공통되는 버그로 생각되어 코멘트 남깁니당 🔥

**Comment by gsandoo** [comment]
수정 완료 (영상 첨부가 어려워 캡쳐 했습니다)

이전
![image](https://github.com/user-attachments/assets/f06225f0-2d62-4020-bb1c-9889fb9369b5)


이후 
![image](https://github.com/user-attachments/assets/e02574a8-cbbd-4410-b923-e59b001a918e)
