### ISSUE TITLE
 [MacOS-Chrome-1920px-헤더] 헤더 css 

### ISSUE THREAD

**Issue by gmlwlsdl** [100-hours-a-week/2-sando-kang-community-issue#19]
**버그 설명**
헤더 css가 모든 페이지에서 동일하지 않습니다. 
title 아무말 대잔치의 경우에는 font size에 비해 할당된 div의 크기가 작은 거 같습니다, 가운데 정렬이 맞지 않는 경우도 있습니다.
그리고 헤더에 padding-bottom이 있는데용 혹시 의도된 부분일까요? 수직으로 정렬을 맞춰주시면 더 깔끔할 거 같습니다!

**스크린샷**
|로그인 페이지|회원가입 페이지|게시글 상세 페이지|
|:---:|:---:|:---:|
|![image](https://github.com/user-attachments/assets/47186dec-d7d9-4329-96f7-b8ed70aeb5f7)|![image](https://github.com/user-attachments/assets/7065e063-d3ab-4718-a3e3-6e103c57c8ca)|![image](https://github.com/user-attachments/assets/4bf5423c-67c3-43f6-b233-485edb4f84d9)|

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 131.0.6778.109(공식 빌드) (arm64)

**Comment by gsandoo** [comment]
padding-bottom 해결 (2024.12.18)
공통화 해결 (2024.12.18)
