### ISSUE TITLE
[Window-Chrome-2880px-게시글 목록] 게시글 날짜 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#2]
**버그 설명**
게시글 목록 화면에서 게시글 생성 날짜가 이상합니다.

**재현하는 방법**
동작을 재현하는 단계:
게시글 상세 페이지에서 확인 가능

**예상한 동작**
2024-12-16 00:00:00 으로 출력될 것이라고 생각했습니다.
**스크린샷**
![image](https://github.com/user-attachments/assets/210c8ce2-e999-4d36-9214-72a79ec1d7ee)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정 완료
