### ISSUE TITLE
 [MacOS-Chrome-1920px-게시글 조회] 프로필 이미지 클릭시 바로 회원 정보 수정 페이지로 이동합니다.

### ISSUE THREAD

**Issue by gmlwlsdl** [100-hours-a-week/2-sando-kang-community-issue#21]
**버그 설명**
프로필 이미지 클릭시 **바로** 회원 정보 수정 페이지로 이동합니다.
토글을 통해 회원 정보 수정 or 비밀번호 수정 or 로그아웃 기능을 사용할 수 있으면 좋을 거 같습니다!

**재현하는 방법**
동작을 재현하는 단계:
1. 우측 상단의 유저 프로필을 클릭한다.

**예상한 동작**
하단에 토글을 통해 회원 정보 수정 or 비밀번호 수정 or 로그아웃 기능을 이용할 수 있다.

**스크린샷**
![무제](https://github.com/user-attachments/assets/5a77d2a5-ed86-4f11-94b6-4c0ab8d7d9b3)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 131.0.6778.109(공식 빌드) (arm64)

**Comment by gsandoo** [comment]
해결 (2024.12.18)
