### ISSUE TITLE
게시글 작성시 내용이 과도하게 많아질 때 발생하는 에러 메시지

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-sando-kang-community-issue#22]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
내용에 많은 양의 문자를 입력한다.

**예상한 동작**
내용 글자 수 초과에 대한 구체적인 에러 메세지를 예상했습니다.

내용의 글자 수를 줄이니 정상적으로 등록되었습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/e41b0fc8-df07-4308-a102-1eca5458681c)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
해결
