### ISSUE TITLE
댓글 작성 시 글자 수가 많아질 때 발생하는 이슈

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-sando-kang-community-issue#23]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
댓글 작성 시 많은 글자 수 입력하고 등록 시 아무런 일도 발생하지 않음

**예상한 동작**
글자 수 초과 시 에러 메시지가 출력될 것으로 예상함

**스크린샷**

https://github.com/user-attachments/assets/76bb3fc2-0a82-4c73-8a2a-4c2805875b90

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
오 감사합니다 조치해 볼게요

**Comment by gsandoo** [comment]
해결
