### ISSUE TITLE
회원정보 수정시 닉네임만 변경할 때 이슈

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-sando-kang-community-issue#24]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:

**예상한 동작**
닉네임만 변경 시 변경될 것으로 예상했지만, 아무런 동작을 하지 않음

**스크린샷**
![image](https://github.com/user-attachments/assets/13e0550f-9e0d-4fa4-8c74-ac64b09a230e)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정 완료
