### ISSUE TITLE
 [MacOS-Chrome-1920px-상세페이지] 댓글 수정 안되는 버그

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-sando-kang-community-issue#25]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
댓글 수정이 안됩니당

**재현하는 방법**
동작을 재현하는 단계:
1. 댓글을 작성한다
2. 댓글 수정 버튼을 누른다
3. 수정한다
4. 댓글수정 버튼을 누른다

**예상한 동작**
작성한 댓글을 수정할 수 있다

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/6a1bc4ff-0d1e-420e-ad76-107581372371)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
확인 후 해결하겠습니다 👍

**Comment by gsandoo** [comment]
[Fix: resolved issue](https://github.com/gsandoo/2-sando-kang-community-be/commit/3b97a80844c282b190549f9894c735f1b2e18063) https://github.com/100-hours-a-week/2-sando-kang-community-be/pull/25
