### ISSUE TITLE
[Window-Chrome-2880px-게시글상세] 좋아요 수정이 불가능 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#3]
**버그 설명**
좋아요를 누르고 나서 좋아요를 취소하고 싶은데, 취소가 불가능합니다.

**재현하는 방법**
동작을 재현하는 단계:
게시글 상세 페이지에서 좋아요 클릭

**예상한 동작**
이미 좋아요를 누른 게시글이라면 좋아요 취소가 될 것 이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/88fe4341-edad-45d8-b32c-2ac76465082f)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정하도록 하겠습니다

**Comment by gsandoo** [comment]
수정 완료 
https://github.com/gsandoo/2-sando-kang-community-fe-react/commit/0f1c80eb78ebf697a36afbaaf16f173a4ad02cf5
