### ISSUE TITLE
댓글/게시글 작성 날짜 및 시간 형식관련 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-sando-kang-community-issue#4]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
- 댓글/게시글 작성 날짜 및 시간 형식 T, Z 그대로 나오는 현상
- 댓글은 시간 00:00:00 으로 고정

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 목록 및 상세 패이지 접근

**예상한 동작**
- 작성날짜가 2024-12-16 11:11 가 나오는걸 예상

**스크린샷**
![image](https://github.com/user-attachments/assets/5ca55cc8-d506-4178-a21a-4873789df2b5)

![image](https://github.com/user-attachments/assets/645bff6d-136a-4a0f-95df-7f7883185521)

**데스크톱(다음 정보를 작성해 주세요):**
 - chrome

**Comment by gsandoo** [comment]
수정 완료
