### ISSUE TITLE
프로필 변경창 기존 프로필 이미지 관련 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-sando-kang-community-issue#6]
**버그 설명**
- 프로필변경 페이지 접근 시 기존 이미지가 보이지 않음

**재현하는 방법**
동작을 재현하는 단계:
1. 프로필 변경 페이지 접근

**예상한 동작**
- 기존 프로필 이미지가 보이는걸 예상

**스크린샷**
![image](https://github.com/user-attachments/assets/22b44f2d-a518-4fbd-b551-705a46451f61)

**데스크톱(다음 정보를 작성해 주세요):**
 - chrome

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정 완료

![image](https://github.com/user-attachments/assets/30ef15da-4709-48bd-85c2-a5333f733c12)

https://github.com/gsandoo/2-sando-kang-community-fe-react/commit/7e7b69be7215b11aad11ade6f19ac1d28d03e587
