### ISSUE TITLE
[Window-Chrome-2880px-게시글 상세] 게시글 상세 페이지 css

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#7]
**버그 설명**
게시글 상세 페이지의 CSS가 이상합니다. 먼저 제목이 중앙에 있지 않으며, 댓글 입력 부분과 게시글 내용과 라인이 맞지 않습니다. 그리고 맨 위에 헤더 부분의 css도 라인이 맞지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
게시글 상세 페이지로 이동

**예상한 동작**
게시글 제목과 헤더 부분은은 중앙에 있고, 댓글 입력 부분과 게시글 상세 부분의 width는 같을 것이라고 생각했습니다. 

**스크린샷**
<img width="430" alt="image" src="https://github.com/user-attachments/assets/6ab9fb68-de4f-4e34-b0b8-640df2f70372" />

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정 완료

![image](https://github.com/user-attachments/assets/fb18a232-6db6-43d9-92b1-3af3429ef2e4)

https://github.com/gsandoo/2-sando-kang-community-fe-react/commit/6b7f1ed88437ac07c9e10794a188017e1e1cdec1
