### ISSUE TITLE
[Window-Chrome-2880px-게시글 상세] 조회수 관련 문의

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#8]
**버그 설명**
게시글을 클릭해서 들어가면 처음에는 조회수가 증가하는데, 한번더 목록으로 이동 후에 접근하면 조회수가 올라가지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인 후, 게시글 리스트 페이지로 이동
2. 게시글 목록에서 게시글을 클릭 후 상세 페이지로 이동
3. 다시 게시글 목록으로 이동 후 동일한 게시글을 클릭하여 상세 페이지로 이동

**예상한 동작**
게시글 상세 페이지에 접근할 때마다 게시글 조회수가 올라갈 것이라고 생각했습니다. (만약 하루에 한번만 올라간다면 그에 대한 제한 시간?이 적용되어있는지 궁금합니다.)

**스크린샷**
![image](https://github.com/user-attachments/assets/cf32abec-c401-40c2-9278-1f5ebcca4506)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
![image](https://github.com/user-attachments/assets/5b6a46e8-2e1b-44db-922d-5ed2d369220b)

개시글 상세 페이지에 접속 시 조회 수 update를 치며 해결하였습니다.
