### ISSUE TITLE
[Window-Chrome-2880px-회원정보 수정] 회원정보 수정 페이지의 프로필 이미지 기본 적용 요청

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-sando-kang-community-issue#9]
**버그 설명**
회원정보 수정에서 프로필 이미지가 보이지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
로그인 후, 회원 정보 수정 페이지로 이동

**예상한 동작**
이전에 등록한 프로필 이미지가 보일 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/bec0ae1d-d718-43e9-975a-719ca6f4bae2)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gsandoo** [comment]
수정 완료
https://github.com/gsandoo/2-sando-kang-community-fe-react/commits/main/
